#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:50:00
#SBATCH --output=update_packages_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate atcs_2024

pip install -U datasets

conda install -c huggingface -c conda-forge datasets

conda install anaconda::nltk
