#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=BiLSTMTrainModel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:59:00
#SBATCH --output=train_BiLSTMMax_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate atcs_2024

srun python -u main.py --encoder_type BiLSTMMax --optimizer SGD --lr 0.1 --lr_decay 0.99 --lr_shrink 5 --minlr 1e-5  --seed 42 --log_dir pl_logs/ 
